### ISSUE TITLE
'FATAL GALVAN EXCEPTION IN HARNESS' in case client sends request while network is partitioned between main and mirror servers.

### ISSUE THREAD

**Issue by yafeldman** [Terracotta-OSS/galvan#106]
Attached tar file with logs and terminal output file.
## Here is error message:

[stripe0][testServer0] Server restarted due to ZAP
[Interlock] serverWasZapped: Server "testServer0": ea591098-6227-44d0-a4a2-f4498688742b
FAIL USING Server "testServer0": ea591098-6227-44d0-a4a2-f4498688742b
org.terracotta.testing.master.GalvanStateInterlock@1ddedee7
    Active: Server "testServer1": 53e3ca64-f140-4bd7-9835-c3236909c099
    Passives: [Server "testServer0": ea591098-6227-44d0-a4a2-f4498688742b]
    Unknown: []
    Terminated: []
    Zapped: []
    Clients: [Thread[Thread-5,5,main]]
XXXXX FATAL GALVAN EXCEPTION IN HARNESS!  TERMINATING PROCESS!  WARNING:  Stale java processes may remain!
java.lang.AssertionError: Case expected to be true
    at org.terracotta.testing.common.Assert.assertTrue(Assert.java:26)
    at org.terracotta.testing.master.GalvanStateInterlock.localAssert(GalvanStateInterlock.java:356)[stripe0][testServer1] 2016-10-21 19:02:40,403 [L2_L2:TCWorkerComm # 2_R] WARN com.tc.net.protocol.transport.ClientMessageTransport - ConnectionID(1.cc0442866e7c42b091132d586b02e399.8c434b58-a799-4d12-891b-50e1efbab429-157e97ae8e6.USER)[]: CLOSE EVENT : com.tc.net.core.TCConnectionImpl@1592421249: connected: false, closed: true local=127.0.0.1:46778 remote=127.0.0.1:2547 connect=[Fri Oct 21 19:02:38 EDT 2016] idle=2325ms [932 read, 1826 write]. STATUS : ESTABLISHED

```
at org.terracotta.testing.master.GalvanStateInterlock.serverWasZapped(GalvanStateInterlock.java:263)
at org.terracotta.testing.master.ServerProcess.instanceWasZapped(ServerProcess.java:261)
at org.terracotta.testing.master.ServerProcess.access$300(ServerProcess.java:43)
at org.terracotta.testing.master.ServerProcess$4.onEvent(ServerProcess.java:236)
at org.terracotta.ipceventbus.event.DefaultEventBus.sendLocal(DefaultEventBus.java:65)
at org.terracotta.ipceventbus.event.DefaultEventBus.trigger(DefaultEventBus.java:59)
at org.terracotta.testing.common.SimpleEventingStream.write(SimpleEventingStream.java:53)
at java.io.OutputStream.write(OutputStream.java:116)
at org.terracotta.ipceventbus.io.MultiplexOutputStream.write(MultiplexOutputStream.java:109)
at org.terracotta.ipceventbus.io.Pipe$1.run(Pipe.java:45)
```

Results :
## Tests run: 0, Failures: 0, Errors: 0, Skipped: 0

**Comment by jd0-sag** [comment]
It looks like the problem here is that galvan only interprets the zap state transition as correct if it happens to a server which isn't yet active or passive.  While this is correct in the normal case, a network interruption should allow this to happen when passive or active, as well.

The change is easy but I need a way to verify it is correct.
