### ISSUE TITLE
Galvan start up issue

### ISSUE THREAD

**Issue by ljacomet** [Terracotta-OSS/galvan#111]
From tests in Ehcache, we have issues with the way Galvan starts the strip initially on setup.

It looks like the servers are started first with `org.terracotta.testing.master.StripeInstaller#startServers` but that does not play well with `org.terracotta.testing.master.SynchronousProcessControl#startAllServers` because the `org.terracotta.testing.master.GalvanStateInterlock` does not seem up to data at that point.

From the safety in place inside `SynchronousProcessControl#startAllServers` we should be able to call it inside the `@Before` of the tests without any issue, but we currently get the following stack trace:

```
java.lang.AssertionError: Case expected to be false
	at org.terracotta.testing.common.Assert.assertFalse(Assert.java:32)
	at org.terracotta.testing.master.ServerProcess.start(ServerProcess.java:98)
	at org.terracotta.testing.master.SynchronousProcessControl.safeStart(SynchronousProcessControl.java:159)
	at org.terracotta.testing.master.SynchronousProcessControl.startAllServers(SynchronousProcessControl.java:101)
	at org.terracotta.testing.rules.BasicExternalCluster$2.startAllServers(BasicExternalCluster.java:253)
	at org.ehcache.clustered.sync.PassiveSyncTest.startServers(PassiveSyncTest.java:58)
```

**Comment by jd0-sag** [comment]
It looks like this is a race during start-up where we start the servers, after installation, but don't wait for them to even start up (produce a PID) before we hand control to the `BasicExternalCluster`.  Therefore, `GalvanStateInterlock` still thinks that it is terminated even though we have requested that it start.

The normal steady state of `SynchronousProcessControl` won't have this problem since it waits for something to enter that `unknownRunning` state before it returns from starting a server.

It looks like the solution will likely be waiting for the servers in the interlock to reach that state before returning control.

It should be relatively straight-forward to create a test to verify this, within Galvan.
