### ISSUE TITLE
Galvan can deadlock controlling servers

### ISSUE THREAD

**Issue by myronkscott** [Terracotta-OSS/galvan#131]
```
===================================================

"Thread-25":

	at org.terracotta.testing.master.GalvanStateInterlock.serverDidShutdown(GalvanStateInterlock.java:235)
	- waiting to lock <0x00000007ad0a6a80> (a org.terracotta.testing.master.TestStateManager)
	at org.terracotta.testing.master.ServerProcess.didTerminateWithStatus(ServerProcess.java:287)
	- locked <0x00000007ad0d2470> (a org.terracotta.testing.master.ServerProcess)
	at org.terracotta.testing.master.ServerProcess.access$400(ServerProcess.java:43)
	at org.terracotta.testing.master.ServerProcess$ExitWaiter.run(ServerProcess.java:403)

"main":

	at org.terracotta.testing.master.ServerProcess.stop(ServerProcess.java:323)
	- waiting to lock <0x00000007ad0d2470> (a org.terracotta.testing.master.ServerProcess)
	at org.terracotta.testing.master.GalvanStateInterlock.safeStop(GalvanStateInterlock.java:351)
	at org.terracotta.testing.master.GalvanStateInterlock.forceShutdown(GalvanStateInterlock.java:328)
	- locked <0x00000007ad0a6a80> (a org.terracotta.testing.master.TestStateManager)
	at org.terracotta.testing.master.BasicHarnessEntry.runOneConfiguration(BasicHarnessEntry.java:81)
	at org.terracotta.testing.master.BasicHarnessEntry.runOneConfiguration(BasicHarnessEntry.java:25)
	at org.terracotta.testing.master.AbstractHarnessEntry.internalRunTestHarness(AbstractHarnessEntry.java:102)
	at org.terracotta.testing.master.AbstractHarnessEntry.runTestHarness(AbstractHarnessEntry.java:41)
	at org.terracotta.testing.support.BasicHarnessRunner.runTest(BasicHarnessRunner.java:37)
	at org.terracotta.testing.support.AbstractHarnessRunner.run(AbstractHarnessRunner.java:92)
	at org.apache.maven.surefire.junit4.JUnit4Provider.execute(JUnit4Provider.java:367)
	at org.apache.maven.surefire.junit4.JUnit4Provider.executeWithRerun(JUnit4Provider.java:274)
	at org.apache.maven.surefire.junit4.JUnit4Provider.executeTestSet(JUnit4Provider.java:238)
	at org.apache.maven.surefire.junit4.JUnit4Provider.invoke(JUnit4Provider.java:161)
	at org.apache.maven.surefire.booter.ForkedBooter.invokeProviderInSameClassLoader(ForkedBooter.java:290)
	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:242)
	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:121)
```

**Comment by myronkscott** [comment]
```
"Process Pipe stdout@6871":
	at org.terracotta.testing.master.GalvanStateInterlock.serverBecamePassive(GalvanStateInterlock.java:224)
	- waiting to lock <0x00000007ad0da598> (a org.terracotta.testing.master.TestStateManager)
	at org.terracotta.testing.master.ServerProcess.didBecomeActive(ServerProcess.java:250)
	- locked <0x00000007ad0e8b70> (a org.terracotta.testing.master.ServerProcess)
	at org.terracotta.testing.master.ServerProcess.access$200(ServerProcess.java:43)
	at org.terracotta.testing.master.ServerProcess$3.onEvent(ServerProcess.java:231)
	at org.terracotta.ipceventbus.event.DefaultEventBus.sendLocal(DefaultEventBus.java:65)
	at org.terracotta.ipceventbus.event.DefaultEventBus.trigger(DefaultEventBus.java:59)
	at org.terracotta.testing.common.SimpleEventingStream.write(SimpleEventingStream.java:53)
	at java.io.OutputStream.write(OutputStream.java:116)
	at org.terracotta.ipceventbus.io.MultiplexOutputStream.write(MultiplexOutputStream.java:109)
	at org.terracotta.ipceventbus.io.Pipe$1.run(Pipe.java:45)
"main":
	at org.terracotta.testing.master.ServerProcess.stop(ServerProcess.java:323)
	- waiting to lock <0x00000007ad0e8b70> (a org.terracotta.testing.master.ServerProcess)
	at org.terracotta.testing.master.GalvanStateInterlock.safeStop(GalvanStateInterlock.java:351)
	at org.terracotta.testing.master.GalvanStateInterlock.forceShutdown(GalvanStateInterlock.java:322)
	- locked <0x00000007ad0da598> (a org.terracotta.testing.master.TestStateManager)
	at org.terracotta.testing.master.BasicHarnessEntry.runOneConfiguration(BasicHarnessEntry.java:81)
	at org.terracotta.testing.master.BasicHarnessEntry.runOneConfiguration(BasicHarnessEntry.java:25)
	at org.terracotta.testing.master.AbstractHarnessEntry.internalRunTestHarness(AbstractHarnessEntry.java:102)
	at org.terracotta.testing.master.AbstractHarnessEntry.runTestHarness(AbstractHarnessEntry.java:41)
	at org.terracotta.testing.support.BasicHarnessRunner.runTest(BasicHarnessRunner.java:37)
	at org.terracotta.testing.support.AbstractHarnessRunner.run(AbstractHarnessRunner.java:92)
	at org.apache.maven.surefire.junit4.JUnit4Provider.execute(JUnit4Provider.java:367)
	at org.apache.maven.surefire.junit4.JUnit4Provider.executeWithRerun(JUnit4Provider.java:274)
	at org.apache.maven.surefire.junit4.JUnit4Provider.executeTestSet(JUnit4Provider.java:238)
	at org.apache.maven.surefire.junit4.JUnit4Provider.invoke(JUnit4Provider.java:161)
	at org.apache.maven.surefire.booter.ForkedBooter.invokeProviderInSameClassLoader(ForkedBooter.java:290)
	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:242)
	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:121)

Found 1 deadlock.
```
