### ISSUE TITLE
NullPointerException in ClientRunner.forceTerminate

### ISSUE THREAD

**Issue by ramsai1729** [Terracotta-OSS/galvan#156]
Looks like a visibility issue

[Clients][client1] Return value (ERROR): 99
[Interlock] clientDidTerminate: Thread[Thread-71,5,main]
[Interlock] > forceShutdown
XXXXX FATAL GALVAN EXCEPTION IN HARNESS!  TERMINATING PROCESS!  WARNING:  Stale java processes may remain!
java.lang.NullPointerException
	at org.terracotta.testing.master.ClientRunner.forceTerminate(ClientRunner.java:134)
	at org.terracotta.testing.master.ClientSubProcessManager.shutDownAndCleanUpClients(ClientSubProcessManager.java:159)
	at org.terracotta.testing.master.ClientSubProcessManager.runTestClients(ClientSubProcessManager.java:151)
	at org.terracotta.testing.master.ClientSubProcessManager.run(ClientSubProcessManager.java:95)

**Comment by ramsai1729** [comment]
Looks like NPE is due to we are trying to forceTerminate the client whose ClientRunner state is not yet initialized properly, in this case `ClientRunner.process` is `null`. `CrashAndHangClientsIT` produces this issue intermittently (https://github.com/Terracotta-OSS/terracotta-core/blob/master/galvan-support/src/test/java/org/terracotta/testing/support/CrashAndHangClientsIT.java)

**Couple of options to fix**
- Wait for proper state before destroying the process 
- Provide a way for clients to wait on other dependent clients
