### ISSUE TITLE
galvan should not bring with it a default logback filename that impacts user-side logging

### ISSUE THREAD

**Issue by mathieucarbou** [Terracotta-OSS/galvan#162]
When running our integration tests in terracotta platform and other places, we have this error each time.

This is because galvan brings at its root classpath a `logback-test.xml` file. With @anthonydahanne we found a lot of issues with that:

1. `logback-test.xml` is a default logback name pattern which overrides the `logback.xml`
2. The content contains a class that might not be available
3. If the goal is to configure galvan logging, perhaps it could be a better idea to have a sort of `logback-galvan.xml` that you use ONLY if the user does not provide a logging file in its classpath.
4. To fix this issue, we are forced as a temporary workaround to put a `logback-test.xml` in our classpath, which will come BEFORE the galvan one to override it

CC @ljacomet @anthonydahanne @GaryWKeim 

```
[Interlock] < waitForActiveServer Server "testServer0": 43beced1-a64a-4b26-b2df-a4a170d01233 (has been zapped: false)
[topology_after_reconfigure(ReconfigureEntityIT)][ProcessControl] <<< waitForActive
[topology_after_reconfigure(ReconfigureEntityIT)][testServer0] 2017-07-17 15:14:29,159 [WorkerThread(request_processor_stage, 3, 3)] INFO com.tc.objectserver.entity.ManagedEntityImpl - Client:ClientID[-1] Invoking lifecycle CREATE_ENTITY on EntityID{className='org.terracotta.management.entity.nms.agent.client.NmsAgentEntity', entityName='NmsAgent'}
[topology_after_reconfigure(ReconfigureEntityIT)][testServer0] 2017-07-17 15:14:29,170 [WorkerThread(request_processor_stage, 3, 3)] INFO com.tc.objectserver.impl.DistributedObjectServer - completed lifecycle CREATE_ENTITY on EntityID{className='org.terracotta.management.entity.nms.agent.client.NmsAgentEntity', entityName='NmsAgent'}
15:14:29,157 |-INFO in ch.qos.logback.classic.LoggerContext[default] - Could NOT find resource [logback.groovy]
15:14:29,157 |-INFO in ch.qos.logback.classic.LoggerContext[default] - Found resource [logback-test.xml] at [jar:file:/Users/matc/.m2/repository/org/terracotta/galvan/1.3.0-pre6/galvan-1.3.0-pre6.jar!/logback-test.xml]
15:14:29,171 |-INFO in ch.qos.logback.core.joran.spi.ConfigurationWatchList@6681fa9 - URL [jar:file:/Users/matc/.m2/repository/org/terracotta/galvan/1.3.0-pre6/galvan-1.3.0-pre6.jar!/logback-test.xml] is not of type file
15:14:29,206 |-INFO in ch.qos.logback.classic.joran.action.ConfigurationAction - debug attribute not set
15:14:29,208 |-INFO in ch.qos.logback.core.joran.action.AppenderAction - About to instantiate appender of type [com.tc.l2.logging.BufferingAppender]
15:14:29,209 |-ERROR in ch.qos.logback.core.joran.action.AppenderAction - Could not create an Appender of type [com.tc.l2.logging.BufferingAppender]. ch.qos.logback.core.util.DynamicClassLoadingException: Failed to instantiate type com.tc.l2.logging.BufferingAppender
	at ch.qos.logback.core.util.DynamicClassLoadingException: Failed to instantiate type com.tc.l2.logging.BufferingAppender
	at 	at ch.qos.logback.core.util.OptionHelper.instantiateByClassNameAndParameter(OptionHelper.java:73)
	at 	at ch.qos.logback.core.util.OptionHelper.instantiateByClassName(OptionHelper.java:48)
	at 	at ch.qos.logback.core.util.OptionHelper.instantiateByClassName(OptionHelper.java:35)
	at 	at ch.qos.logback.core.joran.action.AppenderAction.begin(AppenderAction.java:54)
	at 	at ch.qos.logback.core.joran.spi.Interpreter.callBeginAction(Interpreter.java:275)
	at 	at ch.qos.logback.core.joran.spi.Interpreter.startElement(Interpreter.java:147)
	at 	at ch.qos.logback.core.joran.spi.Interpreter.startElement(Interpreter.java:129)
	at 	at ch.qos.logback.core.joran.spi.EventPlayer.play(EventPlayer.java:50)
	at 	at ch.qos.logback.core.joran.GenericConfigurator.doConfigure(GenericConfigurator.java:149)
	at 	at ch.qos.logback.core.joran.GenericConfigurator.doConfigure(GenericConfigurator.java:135)
	at 	at ch.qos.logback.core.joran.GenericConfigurator.doConfigure(GenericConfigurator.java:99)
	at 	at ch.qos.logback.core.joran.GenericConfigurator.doConfigure(GenericConfigurator.java:49)
	at 	at ch.qos.logback.classic.util.ContextInitializer.configureByResource(ContextInitializer.java:77)
	at 	at ch.qos.logback.classic.util.ContextInitializer.autoConfig(ContextInitializer.java:152)
	at 	at org.slf4j.impl.StaticLoggerBinder.init(StaticLoggerBinder.java:85)
	at 	at org.slf4j.impl.StaticLoggerBinder.<clinit>(StaticLoggerBinder.java:55)
	at 	at org.slf4j.LoggerFactory.bind(LoggerFactory.java:129)
	at 	at org.slf4j.LoggerFactory.performInitialization(LoggerFactory.java:108)
	at 	at org.slf4j.LoggerFactory.getILoggerFactory(LoggerFactory.java:302)
	at 	at org.slf4j.LoggerFactory.getLogger(LoggerFactory.java:276)
	at 	at org.slf4j.LoggerFactory.getLogger(LoggerFactory.java:288)
	at 	at com.tc.config.schema.setup.ClientConfigurationSetupManagerFactory.<clinit>(ClientConfigurationSetupManagerFactory.java:37)
	at 	at com.tc.object.DistributedObjectClientFactory.create(DistributedObjectClientFactory.java:65)
	at 	at com.terracotta.connection.TerracottaInternalClientImpl.init(TerracottaInternalClientImpl.java:68)
	at 	at com.terracotta.connection.api.TerracottaConnectionService.connect(TerracottaConnectionService.java:99)
	at 	at org.terracotta.connection.ConnectionFactory.connect(ConnectionFactory.java:43)
	at 	at org.terracotta.management.integration.tests.AbstractTest.connectManagementClient(AbstractTest.java:174)
	at 	at org.terracotta.management.integration.tests.AbstractTest.commonSetUp(AbstractTest.java:83)
	at 	at org.terracotta.management.integration.tests.AbstractSingleTest.setUp(AbstractSingleTest.java:47)
	at 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at 	at java.lang.reflect.Method.invoke(Method.java:498)
	at 	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at 	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at 	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at 	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:24)
	at 	at org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:27)
	at 	at org.junit.rules.ExternalResource$1.evaluate(ExternalResource.java:48)
	at 	at org.junit.internal.runners.statements.FailOnTimeout$CallableStatement.call(FailOnTimeout.java:298)
	at 	at org.junit.internal.runners.statements.FailOnTimeout$CallableStatement.call(FailOnTimeout.java:292)
	at 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at 	at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.ClassNotFoundException: com.tc.l2.logging.BufferingAppender
	at 	at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
	at 	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at 	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:331)
	at 	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	at 	at ch.qos.logback.core.util.OptionHelper.instantiateByClassNameAndParameter(OptionHelper.java:60)
	at 	... 42 common frames omitted
15:14:29,209 |-ERROR in ch.qos.logback.core.joran.spi.Interpreter@3:72 - ActionException in Action for tag [appender] ch.qos.logback.core.joran.spi.ActionException: ch.qos.logback.core.util.DynamicClassLoadingException: Failed to instantiate type com.tc.l2.logging.BufferingAppender
	at ch.qos.logback.core.joran.spi.ActionException: ch.qos.logback.core.util.DynamicClassLoadingException: Failed to instantiate type com.tc.l2.logging.BufferingAppender
	at 	at ch.qos.logback.core.joran.action.AppenderAction.begin(AppenderAction.java:82)
	at 	at ch.qos.logback.core.joran.spi.Interpreter.callBeginAction(Interpreter.java:275)
	at 	at ch.qos.logback.core.joran.spi.Interpreter.startElement(Interpreter.java:147)
	at 	at ch.qos.logback.core.joran.spi.Interpreter.startElement(Interpreter.java:129)
	at 	at ch.qos.logback.core.joran.spi.EventPlayer.play(EventPlayer.java:50)
	at 	at ch.qos.logback.core.joran.GenericConfigurator.doConfigure(GenericConfigurator.java:149)
	at 	at ch.qos.logback.core.joran.GenericConfigurator.doConfigure(GenericConfigurator.java:135)
	at 	at ch.qos.logback.core.joran.GenericConfigurator.doConfigure(GenericConfigurator.java:99)
	at 	at ch.qos.logback.core.joran.GenericConfigurator.doConfigure(GenericConfigurator.java:49)
	at 	at ch.qos.logback.classic.util.ContextInitializer.configureByResource(ContextInitializer.java:77)
	at 	at ch.qos.logback.classic.util.ContextInitializer.autoConfig(ContextInitializer.java:152)
	at 	at org.slf4j.impl.StaticLoggerBinder.init(StaticLoggerBinder.java:85)
	at 	at org.slf4j.impl.StaticLoggerBinder.<clinit>(StaticLoggerBinder.java:55)
	at 	at org.slf4j.LoggerFactory.bind(LoggerFactory.java:129)
	at 	at org.slf4j.LoggerFactory.performInitialization(LoggerFactory.java:108)
	at 	at org.slf4j.LoggerFactory.getILoggerFactory(LoggerFactory.java:302)
	at 	at org.slf4j.LoggerFactory.getLogger(LoggerFactory.java:276)
	at 	at org.slf4j.LoggerFactory.getLogger(LoggerFactory.java:288)
	at 	at com.tc.config.schema.setup.ClientConfigurationSetupManagerFactory.<clinit>(ClientConfigurationSetupManagerFactory.java:37)
	at 	at com.tc.object.DistributedObjectClientFactory.create(DistributedObjectClientFactory.java:65)
	at 	at com.terracotta.connection.TerracottaInternalClientImpl.init(TerracottaInternalClientImpl.java:68)
	at 	at com.terracotta.connection.api.TerracottaConnectionService.connect(TerracottaConnectionService.java:99)
	at 	at org.terracotta.connection.ConnectionFactory.connect(ConnectionFactory.java:43)
	at 	at org.terracotta.management.integration.tests.AbstractTest.connectManagementClient(AbstractTest.java:174)
	at 	at org.terracotta.management.integration.tests.AbstractTest.commonSetUp(AbstractTest.java:83)
	at 	at org.terracotta.management.integration.tests.AbstractSingleTest.setUp(AbstractSingleTest.java:47)
	at 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at 	at java.lang.reflect.Method.invoke(Method.java:498)
	at 	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at 	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at 	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at 	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:24)
	at 	at org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:27)
	at 	at org.junit.rules.ExternalResource$1.evaluate(ExternalResource.java:48)
	at 	at org.junit.internal.runners.statements.FailOnTimeout$CallableStatement.call(FailOnTimeout.java:298)
	at 	at org.junit.internal.runners.statements.FailOnTimeout$CallableStatement.call(FailOnTimeout.java:292)
	at 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at 	at java.lang.Thread.run(Thread.java:745)
Caused by: ch.qos.logback.core.util.DynamicClassLoadingException: Failed to instantiate type com.tc.l2.logging.BufferingAppender
	at 	at ch.qos.logback.core.util.OptionHelper.instantiateByClassNameAndParameter(OptionHelper.java:73)
	at 	at ch.qos.logback.core.util.OptionHelper.instantiateByClassName(OptionHelper.java:48)
	at 	at ch.qos.logback.core.util.OptionHelper.instantiateByClassName(OptionHelper.java:35)
	at 	at ch.qos.logback.core.joran.action.AppenderAction.begin(AppenderAction.java:54)
	at 	... 39 common frames omitted
Caused by: java.lang.ClassNotFoundException: com.tc.l2.logging.BufferingAppender
	at 	at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
	at 	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at 	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:331)
	at 	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	at 	at ch.qos.logback.core.util.OptionHelper.instantiateByClassNameAndParameter(OptionHelper.java:60)
	at 	... 42 common frames omitted
15:14:29,209 |-INFO in ch.qos.logback.core.joran.action.AppenderAction - About to instantiate appender of type [ch.qos.logback.core.ConsoleAppender]
15:14:29,215 |-INFO in ch.qos.logback.core.joran.action.AppenderAction - Naming appender as [SYSOUT]
15:14:29,230 |-INFO in ch.qos.logback.core.joran.action.NestedComplexPropertyIA - Assuming default type [ch.qos.logback.classic.encoder.PatternLayoutEncoder] for [encoder] property
15:14:29,253 |-INFO in ch.qos.logback.classic.joran.action.RootLoggerAction - Setting level of ROOT logger to INFO
15:14:29,253 |-ERROR in ch.qos.logback.core.joran.action.AppenderRefAction - Could not find an appender named [TC_BASE]. Did you define it below instead of above in the configuration file?
15:14:29,253 |-ERROR in ch.qos.logback.core.joran.action.AppenderRefAction - See http://logback.qos.ch/codes.html#appender_order for more details.
15:14:29,253 |-INFO in ch.qos.logback.core.joran.action.AppenderRefAction - Attaching appender named [SYSOUT] to Logger[ROOT]
15:14:29,253 |-INFO in ch.qos.logback.classic.joran.action.ConfigurationAction - End of configuration.
15:14:29,254 |-INFO in ch.qos.logback.classic.joran.JoranConfigurator@3a7690ed - Registering current configuration as safe fallback point

2017-07-17 15:14:29,334 [Time-limited test] INFO com.tc.net.protocol.transport.ConnectionHealthCheckerImpl: TC Client - HealthChecker Started
```

**Comment by henri-tremblay** [comment]
Indeed, galvan should not provide any `logback.xml` file. If it wants to give some default, logback does support includes. So having a logback-galvan.xml make sense. It can then be included with `<include resource="org/terracotta/logback/logback-galvan.xml"/>`.
