### ISSUE TITLE
Shepherding Thread logs "java.lang.IllegalStateException: Tried to use an already shut down SynchronousProcessControl object" if test shuts down server

### ISSUE THREAD

**Issue by cljohnso** [Terracotta-OSS/galvan#34]
A test like the one shown below intentionally shuts down the server (to test "missing" server operation) but logs the following exception when the test ends:

````text
Exception in thread "Shepherding Thread" java.lang.IllegalStateException: Tried to use an already shut down SynchronousProcessControl object
	at org.terracotta.testing.master.SynchronousProcessControl.verifyNotShutdown(SynchronousProcessControl.java:220)
	at org.terracotta.testing.master.SynchronousProcessControl.shutDown(SynchronousProcessControl.java:90)
	at org.terracotta.testing.rules.BasicExternalCluster$1.forceTerminateComponent(BasicExternalCluster.java:111)
	at org.terracotta.testing.master.TestStateManager.waitForFinish(TestStateManager.java:45)
	at org.terracotta.testing.rules.BasicExternalCluster$2.run(BasicExternalCluster.java:130)
````

The test seems to operate as expected in all respects other than this exception being logged.  Since the test explicitly shuts down the server, this exception seems to be just noise.

----

````java
public class TerminatedServerTest {

  private static final String RESOURCE_CONFIG =
      "<service xmlns:ohr='http://www.terracotta.org/config/offheap-resource' id=\"resources\">"
          + "<ohr:offheap-resources>"
          + "<ohr:resource name=\"primary-server-resource\" unit=\"MB\">64</ohr:resource>"
          + "</ohr:offheap-resources>" +
          "</service>\n";

  @Rule
  public final TestName testName = new TestName();

  @Rule
  public final Cluster cluster =
      new BasicExternalCluster(new File("build/cluster"), 1, Collections.<File>emptyList(), "", RESOURCE_CONFIG, null);

  @Before
  public void waitForActive() throws Exception {
    cluster.getClusterControl().waitForActive();
  }

  @Test
  public void testTerminationBeforeCacheManagerClose() throws Exception {
    CacheManagerBuilder<PersistentCacheManager> clusteredCacheManagerBuilder =
        CacheManagerBuilder.newCacheManagerBuilder()
        .with(TestClusteringServiceConfigurationBuilder.cluster(cluster.getConnectionURI().resolve("/MyCacheManagerName?auto-create"))
            .defaultServerResource("primary-server-resource"));
    PersistentCacheManager cacheManager = clusteredCacheManagerBuilder.build(false);
    cacheManager.init();

    cluster.getClusterControl().tearDown();

    // ... other stuff ...
  }
}
````

**Comment by jd0-sag** [comment]
This will probably be clearer when #30 is resolved but the core issue is that calling `tearDown()` from within a test is problematic since it really means that the test environment should be torn down.  I suspect that a solution to #30 would more directly address what such a test is actually trying to do.

In fact, the `tearDown()` method should probably be removed from `IClusterControl` since the nature of how to shut down the test environment is directly connected to how it was set up so there isn't really any generalization win by making this part of the common interface (a clue to this is that there is no corresponding "`setup()`" method).

**Comment by jd0-sag** [comment]
Closing this now that #30 has been addressed, removing the `tearDown()` method while providing more appropriate termination routines to get this effect in an explicitly defined way.
