### ISSUE TITLE
BasicExternalServer.after hangs waiting for ps output

### ISSUE THREAD

**Issue by cljohnso** [Terracotta-OSS/galvan#46]
The `BasicExternalCluster.after` stalls waiting for completion of the "Shepherding Thread".  The "Shepherding Thread" is stalled waiting on completion of the `ps -eww -o pid,command` in `killProcessUnix`.  Completion of the `ps` process is waiting on consumption of it's output.  The stall is dependent on the amount of output produced from the `ps` command.

For a `Process` to complete, enough of its output (STDERR or STDOUT) must be consumed to allow the underlying UNIX process to complete -- otherwise it is blocked on writing output to its "full" buffers.

The `killProcessUnix' method needs to consume effectively all of the `ps` output **before** calling `Process.waitFor` to prevent a hang.  (In this case STDERR is not the culprit but very well could have been ... consider using `ProcessBuilder` and `redirectErrorStream(boolean)` to avoid a STDERR-cause stall.)

This fault is presently preventing Ehcache3 builds from completing.  

The attached [patch](https://github.com/Terracotta-OSS/galvan/files/338295/ps_stall.txt) is a hack that works locally.

----

```text
"Test worker" #11 prio=5 os_prio=31 tid=0x00007ffcdbcc9000 nid=0x5503 in Object.wait() [0x000000011f95e000]
   java.lang.Thread.State: WAITING (on object monitor)
	at java.lang.Object.wait(Native Method)
	at java.lang.Thread.join(Thread.java:1245)
	- locked <0x00000007a002ec58> (a org.terracotta.testing.rules.BasicExternalCluster$2)
	at java.lang.Thread.join(Thread.java:1319)
	at org.terracotta.testing.rules.BasicExternalCluster.after(BasicExternalCluster.java:155)
	at org.junit.rules.ExternalResource$1.evaluate(ExternalResource.java:50)
	at org.junit.rules.RunRules.evaluate(RunRules.java:20)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.gradle.api.internal.tasks.testing.junit.JUnitTestClassExecuter.runTestClass(JUnitTestClassExecuter.java:114)
	at org.gradle.api.internal.tasks.testing.junit.JUnitTestClassExecuter.execute(JUnitTestClassExecuter.java:57)
	at org.gradle.api.internal.tasks.testing.junit.JUnitTestClassProcessor.processTestClass(JUnitTestClassProcessor.java:66)
	at org.gradle.api.internal.tasks.testing.SuiteTestClassProcessor.processTestClass(SuiteTestClassProcessor.java:51)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at org.gradle.internal.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:35)
	at org.gradle.internal.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:24)
	at org.gradle.internal.dispatch.ContextClassLoaderDispatch.dispatch(ContextClassLoaderDispatch.java:32)
	at org.gradle.internal.dispatch.ProxyDispatchAdapter$DispatchingInvocationHandler.invoke(ProxyDispatchAdapter.java:93)
	at com.sun.proxy.$Proxy2.processTestClass(Unknown Source)
	at org.gradle.api.internal.tasks.testing.worker.TestWorker.processTestClass(TestWorker.java:109)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at org.gradle.internal.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:35)
	at org.gradle.internal.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:24)
	at org.gradle.internal.remote.internal.hub.MessageHub$Handler.run(MessageHub.java:377)
	at org.gradle.internal.concurrent.ExecutorPolicy$CatchAndRecordFailures.onExecute(ExecutorPolicy.java:54)
	at org.gradle.internal.concurrent.StoppableExecutorImpl$1.run(StoppableExecutorImpl.java:40)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
   Locked ownable synchronizers:	- <0x00000007a0032f20> (a java.util.concurrent.ThreadPoolExecutor$Worker)
```

```text
"Shepherding Thread" #21 prio=5 os_prio=31 tid=0x00007ffcdcdba800 nid=0x6503 in Object.wait() [0x000000011f737000]
   java.lang.Thread.State: WAITING (on object monitor)
	at java.lang.Object.wait(Native Method)
	at java.lang.Object.wait(Object.java:502)
	at java.lang.UNIXProcess.waitFor(UNIXProcess.java:396)
	- locked <0x00000007be4fa9c0> (a java.lang.UNIXProcess)
	at org.terracotta.testing.master.ServerProcess$ExitWaiter.killProcessUnix(ServerProcess.java:278)
	at org.terracotta.testing.master.ServerProcess$ExitWaiter.bringDownServer(ServerProcess.java:250)
	- locked <0x00000007a002f1c8> (a org.terracotta.testing.master.ServerProcess$ExitWaiter)
	at org.terracotta.testing.master.ServerProcess.stop(ServerProcess.java:160)
	at org.terracotta.testing.master.SynchronousProcessControl.shutdownServer(SynchronousProcessControl.java:209)
	at org.terracotta.testing.master.SynchronousProcessControl.shutDown(SynchronousProcessControl.java:154)
	- locked <0x00000007a003d270> (a org.terracotta.testing.master.SynchronousProcessControl)
	at org.terracotta.testing.rules.BasicExternalCluster$1.forceTerminateComponent(BasicExternalCluster.java:111)
	at org.terracotta.testing.master.TestStateManager.waitForFinish(TestStateManager.java:45)
	- locked <0x00000007a002edd8> (a org.terracotta.testing.master.TestStateManager)
	at org.terracotta.testing.rules.BasicExternalCluster$2.run(BasicExternalCluster.java:130)
   Locked ownable synchronizers:	- None
```

**Comment by jd0-sag** [comment]
What is it actually waiting for, in this case?  Is it specific to some machine or test since the galvan tests passed this.

It looks like the problem (and why this might not be detected in some testing environments) may be related to the amount of data buffered by the reader:

      BufferedReader outputReader = new BufferedReader(new InputStreamReader(ps.getInputStream()));

To resolve that problem, we probably just need to move the waitFor to be after the loop.

The ProcessBuilder suggestion to handle the STDERR case is a good one, though, so I will also give that a shot.  I will prototype this and hopefully it can be resolved soon.
